
weather.visualcrossing.url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/
weather.visualcrossing.key=<YOUR_API_KEY>
# Create free account on https://www.visualcrossing.com/weather-data-editions and copy the key from `My Account` section

